[package]
edition.workspace = true
name = "rax-utils"
version.workspace = true

[dependencies]
clerk = { workspace = true }
miette = { workspace = true }
serialport = { workspace = true }

[dev-dependencies]
clerk = { workspace = true, features = ["log"] }

[features]
log = ["clerk/log"]
