[package]
name = "dux-max7219"
version = "0.1.0"
edition.workspace = true

[dependencies]
defmt = { workspace = true, optional = true }
embedded-hal = { workspace = true }
embedded-hal-async = { workspace = true, optional = true }
paste = { workspace = true }
thiserror = { workspace = true }

[features]
async = ["embedded-hal-async"]
defmt = ["dep:defmt"]
