[package]
edition.workspace = true
name = "on-board-led"
version = "0.1.0"

[dependencies]
esp-backtrace = { workspace = true, features = [
  "esp32c3",
  "panic-handler",
  "exception-handler",
  "println",
] }
esp-bootloader-esp-idf = { workspace = true }
esp-hal = { workspace = true, features = ["esp32c3", "unstable"] }
esp-hal-smartled = { workspace = true, features = ["esp32c3"] }
esp-println = { workspace = true, features = ["esp32c3"] }
smart-leds = { workspace = true }

