[package]
edition.workspace = true
name = "dux-sht4x"
version = "0.1.0"

[dependencies]
embedded-hal = { workspace = true }
fixed = { workspace = true }
sensirion-i2c = { workspace = true }
thiserror = { workspace = true }
embedded-hal-async = { workspace = true, optional = true }
[features]
async = ["embedded-hal-async"]
