[package]
edition.workspace = true
name = "rax-nmea"
version.workspace = true

[dependencies]
chrono = { workspace = true }
clerk = { workspace = true }
miette = { workspace = true }
rax-parser = { workspace = true }
serde = { workspace = true }

[dev-dependencies]
float-cmp = { workspace = true }
serialport = { workspace = true }
test-utils = { workspace = true }

[features]
log = ["clerk/log"]
