[package]
edition.workspace = true
name = "rax-nmea"
version.workspace = true

[dependencies]
chrono = { workspace = true }
clerk = { workspace = true }
miette = { workspace = true }
rax-parser = { workspace = true }
serde = { workspace = true }

[dev-dependencies]
clerk = { workspace = true, features = ["log"] }
float-cmp = { workspace = true }
serialport = { workspace = true }

[features]
log = ["clerk/log"]
