[package]
edition.workspace = true
name = "hygrothermograph"
version = "0.1.0"

[dependencies]
dux-sht4x = { workspace = true }
embedded-hal-bus = { workspace = true }
esp-alloc = { workspace = true }
esp-bootloader-esp-idf = { workspace = true }
esp-hal = { workspace = true }
esp-println = { workspace = true }
heapless = { workspace = true }
i2c-character-display = { workspace = true }
mischief = { workspace = true }
pain = { workspace = true }
riscv = { workspace = true }

[package.metadata.cargo-machete]
ignored = ["esp-println"]
