[workspace]
members = ["./crates/*"]
resolver = "2"

[workspace.package]
edition = "2024"

[workspace.dependencies]
esp-backtrace = "0.17.0"
esp-bootloader-esp-idf = "0.1.0"
esp-hal = "1.0.0-rc.0"
esp-hal-smartled = { git = "https://github.com/esp-rs/esp-hal-community" }
esp-println = "0.15.0"
micromath = "2.1.0"
smart-leds = "0.4"
embedded-hal = "1.0.0"
i2c-character-display = { version = "0.5", features = ["defmt"] }
sht4x = "0.2.0"
embedded-hal-bus = "0.3.0"
heapless = "0.9.1"

[profile.dev]
opt-level = 3
overflow-checks = true

[profile.release]
codegen-units = 1
debug = false
lto = "fat"
opt-level = 3
overflow-checks = false
