version = 1

[envs.base]
channels = ["https://repo.prefix.dev/glatzel", "conda-forge"]

[envs.base.dependencies]
aria2 = "*"
bottom = "*"
curl = "*"
edit = "*"
jq = "*"
p7zip = "*"
wget = "*"
yazi = "*"
zstd = "*"

[envs.base.exposed]
7z = "7z"
aria2c = "aria2c"
btm = "btm"
curl = "curl"
edit = "edit"
jq = "jq"
wget = "wget"
yazi = "yazi"
zstd = "zstd"
