[package]
edition.workspace = true
name = "gps"
version.workspace = true

[dependencies]
clerk = { workspace = true, features = ["log"] }
nmea = { workspace = true }
serialport = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
