[workspace]
resolver = "3"
members = ["./crates/*"]

[workspace.package]
edition = "2024"

[workspace.dependencies]
defmt = "1.1.1"
embedded-hal = "1.0.0"
embedded-hal-async = "1.0.0"
fixed = "1.31.0"
paste = "1.0.15"
sensirion-i2c = "0.4.0"
thiserror = { version = "2.0.19", default-features = false }

[profile.release]
opt-level = 3
debug = false
strip = true
lto = "fat"
codegen-units = 1
