[package]
edition.workspace = true
name = "esp32-c3-zero-example"
version = "0.1.0"

[dependencies]
esp-bootloader-esp-idf = { workspace = true }
esp-hal = { workspace = true }
esp-hal-smartled = { workspace = true }
esp-println = { workspace = true }
micromath = { workspace = true }
smart-leds = { workspace = true }
i2c-character-display = { workspace = true }
riscv = { workspace = true }
mischief= { workspace = true }
esp-alloc = { workspace = true }
esp-backtrace = { version = "0.17.0", features = [
    "esp32c3",
    "panic-handler",
    "exception-handler",
    "println",
], optional = true }
