version = 1

[envs.dev-tool]
channels = ["https://repo.prefix.dev/glatzel", "conda-forge"]

[envs.dev-tool.dependencies]
aria2 = "*"
bottom = "*"
edit = "*"
jq = "*"
p7zip = "*"
zstd = "*"

[envs.dev-tool.exposed]
7z = "7z"
aria2 = "aria2c"
btm = "btm"
edit = "edit"
jq = "jq"
zstd = "zstd"
