name: CI

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches: [main]
    paths-ignore:
      - "*.md"
  pull_request:
    types:
      - opened
      - synchronize
      - ready_for_review
    paths-ignore:
      - "*.md"

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name != 'push'}}

jobs:
  lefthook:
    uses: ./.github/workflows/ci-lefthook.yml
    permissions:
      contents: write
      pull-requests: write
  changed:
    outputs:
      changed-driver: ${{ steps.main.outputs.driver_any_changed }}
      changed-esp32-c3: ${{ steps.main.outputs.esp32-c3_any_changed }}
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        if: ${{github.event_name == 'pull_request'}}
      - id: main
        uses: tj-actions/changed-files@9426d40962ed5378910ee2e21d5f8c6fcbf2dd96 # v47.0.6
        if: ${{github.event_name == 'pull_request'}}
        with:
          files_yaml: |
            driver:
              - ./driver/**
              - ./.github/**
            esp32-c3:
              - ./esp32-c3/**
              - ./.github/**

  build-esp32-c3:
    needs: changed
    strategy:
      fail-fast: false
      matrix:
        args:
          - ""
          - "--release"
    if: ${{ needs.changed.outputs.changed-esp32-c3 != 'false' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: ./.github/actions/rust/setup-rust
        with:
          targets: riscv32imc-unknown-none-elf
      - uses: ./.github/actions/rust/cargo-build
        with:
          working-directory: ./esp32-c3
          args: ${{matrix.args}}

  clippy-esp32-c3:
    needs: changed
    if: ${{ needs.changed.outputs.changed-esp32-c3 != 'false' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: ./.github/actions/rust/setup-rust
        with:
          components: clippy
          targets: riscv32imc-unknown-none-elf
      - uses: ./.github/actions/rust/cargo-clippy
        with:
          working-directory: ./esp32-c3

  test-driver:
    needs: changed
    strategy:
      fail-fast: false
      matrix:
        args:
          - "--workspace"
          - "--workspace --features async"
    if: ${{ needs.changed.outputs.changed-driver != 'false' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: ./.github/actions/rust/setup-rust
        with:
          toolchain: nightly
          components: clippy
      - uses: ./.github/actions/rust/cargo-clippy
        with:
          working-directory: ./driver
          args: ${{matrix.args}}
      - uses: ./.github/actions/rust/cargo-test
        with:
          working-directory: ./driver
          nextest-args: ${{matrix.args}}
          examples: false
          doc: false
      - uses: ./.github/actions/common/codecov
        if: ${{ !cancelled() }}

  check-point:
    if: ( cancelled() || failure() ) && github.event_name == 'pull_request'
    needs: [lefthook, test-driver, build-esp32-c3, clippy-esp32-c3, changed]
    runs-on: ubuntu-slim
    steps:
      - run: exit 1
