name: CI

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches: [main]
    paths-ignore:
      - "*.md"
  pull_request:
    types:
      - opened
      - synchronize
      - ready_for_review
    paths-ignore:
      - "*.md"

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name != 'push'}}

jobs:
  lefthook:
    if: ${{ github.event_name != 'schedule' }}
    uses: ./.github/workflows/ci-lefthook.yml
    permissions:
      contents: write
      pull-requests: write
  changed:
    outputs:
      changed-driver: ${{ steps.main.outputs.driver_any_changed }}
      changed-esp32-c3: ${{ steps.main.outputs.esp32-c3_any_changed }}
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        if: ${{github.event_name == 'pull_request'}}
      - id: main
        uses: tj-actions/changed-files@9426d40962ed5378910ee2e21d5f8c6fcbf2dd96 # v47.0.6
        if: ${{github.event_name == 'pull_request'}}
        with:
          files_yaml: |
            driver:
              - ./driver/**
              - ./.github/**
            esp32-c3:
              - ./esp32-c3/**
              - ./.github/**

  build-esp32-c3:
    needs: changed
    strategy:
      fail-fast: false
      matrix:
        options:
          -
          - --release
    if: ${{ needs.changed.outputs.changed-esp32-c3 != 'false' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: Glatzel/template/.github/actions/rust/setup-rust@87fb72378e1351f8e78d884443e60f6dcbf15df8 # v2026.9.3
        with:
          targets: riscv32imc-unknown-none-elf
      - uses: Glatzel/template/.github/actions/rust/cargo-build@87fb72378e1351f8e78d884443e60f6dcbf15df8 # v2026.9.3
        with:
          working-directory: ./esp32-c3
          options: ${{matrix.options}}

  clippy-esp32-c3:
    needs: changed
    if: ${{ needs.changed.outputs.changed-esp32-c3 != 'false' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: Glatzel/template/.github/actions/rust/setup-rust@87fb72378e1351f8e78d884443e60f6dcbf15df8 # v2026.9.3
        with:
          components: clippy
          targets: riscv32imc-unknown-none-elf
      - uses: Glatzel/template/.github/actions/rust/cargo-clippy@87fb72378e1351f8e78d884443e60f6dcbf15df8 # v2026.9.3
        with:
          working-directory: ./esp32-c3

  test-driver:
    needs: changed
    strategy:
      fail-fast: false
      matrix:
        options:
          - "--workspace"
          - "--workspace --features async"
    if: ${{ needs.changed.outputs.changed-driver != 'false' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: Glatzel/template/.github/actions/rust/setup-rust@87fb72378e1351f8e78d884443e60f6dcbf15df8 # v2026.9.3
        with:
          toolchain: nightly
          components: clippy
      - uses: Glatzel/template/.github/actions/rust/cargo-clippy@87fb72378e1351f8e78d884443e60f6dcbf15df8 # v2026.9.3
        with:
          working-directory: ./driver
          options: ${{matrix.options}}
      - uses: Glatzel/template/.github/actions/rust/cargo-test@87fb72378e1351f8e78d884443e60f6dcbf15df8 # v2026.9.3
        with:
          working-directory: ./driver
          nextest-options: ${{matrix.options}}
          examples: false
          doc: false
      - uses: Glatzel/template/.github/actions/common/codecov@87fb72378e1351f8e78d884443e60f6dcbf15df8 # v2026.9.3
        if: ${{ !cancelled() }}

  check-point:
    if: ( cancelled() || failure() ) && github.event_name == 'pull_request'
    needs: [ lefthook, test-driver, build-esp32-c3, clippy-esp32-c3, changed]
    runs-on: ubuntu-slim
    steps:
      - run: exit 1
