name: CI

on:
  workflow_dispatch:

permissions: read-all

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: cross-build
        run: ./scripts/cross-build.ps1 -Release
        shell: pwsh

      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: deploy-aarch64
          path: |
            ./deploy
          if-no-files-found: error