name: deploy-linux-aarch64

on:
  workflow_dispatch:

permissions: read-all

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up pixi
        uses: prefix-dev/setup-pixi@v0.8.10
        with:
          run-install: false
      - name: cross-build
        run: ./scripts/cross-build-linux-aarch64 -Release
        shell: pwsh

      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: cross-build-linux-aarch64
          path: |
            ./deploy/linux-aarch64
          if-no-files-found: error
